### ISSUE TITLE
I would love to try this out!

### ISSUE THREAD

**Issue by Deadlander** [RhombusWeasel/Deadlands-Classic#4]
I would love to try your build out, as I am an avid DL Classic player, but I have no idea how to install it without the system being added to the Foundry's list.  How would I go about this?

**Comment by RhombusWeasel** [comment]
Hi,  if you paste this link into the text input at the bottom of the install game systems screen then it should just add it for you and then auto update.
https://raw.githubusercontent.com/RhombusWeasel/Deadlands-Classic/main/system.json

**Comment by RhombusWeasel** [comment]
![manifest](https://user-images.githubusercontent.com/36423296/103492814-7c3c1180-4e25-11eb-9476-e1009dece3de.PNG)

**Comment by Deadlander** [comment]
That worked!  Awesome and thanks!

**Comment by Deadlander** [comment]
Also, is there a similar link for the Exploding dice mod?

**Comment by RhombusWeasel** [comment]
https://raw.githubusercontent.com/RhombusWeasel/Deadlands-Classic-Dice-Explosion/main/module.json

**Comment by Deadlander** [comment]
Thank you again!

**Comment by RhombusWeasel** [comment]
No problem, if you have any issues or feature requests just let me know.

**Comment by Deadlander** [comment]
I do have one question.  What is the -8 penalty for on the Character sheet?  I know that was the original way to do it with the original release, but with the Players' Guide in 1999, it was changed to a -4 penalty on 1 die of the Trait.
