### ISSUE TITLE
Default rolls needs updated to newer set up.

### ISSUE THREAD

**Issue by Deadlander** [RhombusWeasel/Deadlands-Classic#6]
It seems that the current default roll for Aptitudes is set to the original release default.  The current version uses 1 die of the Trait with a -4 penalty rather than a full trait roll with a -8 penalty.

Also, feel free to add me on Discord.  My user name is James Smith#0343.  I have been playing Deadlands Classic since 1996 and have a very solid feel for the system from many, many conversations with Shane H and John G.

**Comment by RhombusWeasel** [comment]
Hi I've hit you up on Discord, I'm going to look into making these types of erratas optional in a config setting.
I wasn't aware of that one but it seems easy enough to implement, are there any others you can think of off the top of your head?

**Comment by RhombusWeasel** [comment]
Finally added this as a config option on the last update.  Closing.
